-- This script was generated by a beta version of the ERD tool in pgAdmin 4.
-- Please log an issue at https://redmine.postgresql.org/projects/pgadmin4/issues/new if you find any bugs, including reproduction steps.
BEGIN;


CREATE TABLE IF NOT EXISTS public.yazar
(
    yazar_id serial NOT NULL,
    yazar_adi character varying,
    yazar_soyadi character varying,
    PRIMARY KEY (yazar_id)
);

CREATE TABLE IF NOT EXISTS public.kitap
(
    kitap_id serial NOT NULL,
    kitap_adi character varying,
    kitap_fiyati character varying,
    PRIMARY KEY (kitap_id)
);

ALTER TABLE public.kitap
    ADD FOREIGN KEY (kitap_id)
    REFERENCES public.yazar (yazar_id)
    NOT VALID;

END;