-- This script was generated by a beta version of the ERD tool in pgAdmin 4.
-- Please log an issue at https://redmine.postgresql.org/projects/pgadmin4/issues/new if you find any bugs, including reproduction steps.
BEGIN;


CREATE TABLE IF NOT EXISTS public.admin
(
    admin_id serial NOT NULL,
    admin_name character varying,
    admin_surname character varying,
    admin_tel_number character varying,
    admin_email_addres character varying,
    admin_password character varying,
    admin_number_of_records integer,
    "created_Date" date,
    PRIMARY KEY (admin_id)
);

CREATE TABLE IF NOT EXISTS public."user"
(
    user_id serial NOT NULL,
    user_name character varying,
    user_surname character varying,
    user_tel_number character varying,
    user_email_address character varying,
    user_password character varying,
    user_is_active boolean,
    user_hescode character varying,
    created_date date,
    admin_id integer NOT NULL,
    PRIMARY KEY (user_id)
);

ALTER TABLE public."user"
    ADD FOREIGN KEY (admin_id)
    REFERENCES public.admin (admin_id)
    NOT VALID;

END;